FROM node:20-bookworm-slim AS deps
WORKDIR /app

# Install timezone data and set timezone
# RUN apk add --no-cache tzdata \
#   && cp /usr/share/zoneinfo/Africa/Lagos /etc/localtime \
#   && echo "Africa/Lagos" > /etc/timezone

# Install dependencies first to maximize Docker layer caching
COPY package.json ./
RUN npm install --no-audit --no-fund --legacy-peer-deps --include=dev

COPY . .

RUN npm run build

# # Remove dev dependencies after building
# RUN npm prune --omit=dev

# FROM node:20-bookworm-slim AS runtime
# WORKDIR /app

# Expose the port the app runs on in the container
EXPOSE 4400

# Define the environment variables (for Coolify / build args)
ARG NODE_ENV
ARG HOST
ARG PORT
ARG DATABASE_URL

ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG REFRESH_TOKEN_SECRET
ARG REFRESH_TOKEN_EXPIRES_IN
ARG ACCESS_COOKIE_MAX_AGE
ARG REFRESH_COOKIE_MAX_AGE
ARG TOKEN_COOKIE_ACCESS
ARG TOKEN_COOKIE_REFRESH

ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET

ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG REDIS_DB
ARG REDIS_URL
ARG CACHE_EXPIRY

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG S3_BUCKET_NAME

ARG R2_ACCOUNT_ID
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_BUCKET_NAME
ARG R2_FOLDER_PREFIX
ARG R2_CDN_URL
ARG R2_PUBLIC_URL

ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_SECURE
ARG SMTP_USER
ARG SMTP_PASS
ARG EMAIL_FROM
ARG EMAIL_FROM_NAME

ARG APP_NAME
ARG PRIMARY_COLOR
ARG SECONDARY_COLOR
ARG FONT_FAMILY
ARG SUPPORT_EMAIL
ARG LOGO_URL

ARG CORS_ORIGIN
ARG RATE_LIMIT_MAX
ARG RATE_LIMIT_TIME_WINDOW

ARG ADMIN_APP_URL
ARG CLIENT_APP_URL

# Set environment variables
ENV NODE_ENV=production \
  HOST=$HOST \
  PORT=$PORT \
  DATABASE_URL=$DATABASE_URL \
  JWT_SECRET=$JWT_SECRET \
  JWT_EXPIRES_IN=$JWT_EXPIRES_IN \
  REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET \
  REFRESH_TOKEN_EXPIRES_IN=$REFRESH_TOKEN_EXPIRES_IN \
  ACCESS_COOKIE_MAX_AGE=$ACCESS_COOKIE_MAX_AGE \
  REFRESH_COOKIE_MAX_AGE=$REFRESH_COOKIE_MAX_AGE \
  TOKEN_COOKIE_ACCESS=$TOKEN_COOKIE_ACCESS \
  TOKEN_COOKIE_REFRESH=$TOKEN_COOKIE_REFRESH \
  GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
  GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
  REDIS_HOST=$REDIS_HOST \
  REDIS_PORT=$REDIS_PORT \
  REDIS_PASSWORD=$REDIS_PASSWORD \
  REDIS_DB=$REDIS_DB \
  REDIS_URL=$REDIS_URL \
  CACHE_EXPIRY=$CACHE_EXPIRY \
  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  AWS_REGION=$AWS_REGION \
  S3_BUCKET_NAME=$S3_BUCKET_NAME \
  R2_ACCOUNT_ID=$R2_ACCOUNT_ID \
  R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID \
  R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY \
  R2_BUCKET_NAME=$R2_BUCKET_NAME \
  R2_FOLDER_PREFIX=$R2_FOLDER_PREFIX \
  R2_CDN_URL=$R2_CDN_URL \
  R2_PUBLIC_URL=$R2_PUBLIC_URL \
  SMTP_HOST=$SMTP_HOST \
  SMTP_PORT=$SMTP_PORT \
  SMTP_SECURE=$SMTP_SECURE \
  SMTP_USER=$SMTP_USER \
  SMTP_PASS=$SMTP_PASS \
  EMAIL_FROM=$EMAIL_FROM \
  EMAIL_FROM_NAME=$EMAIL_FROM_NAME \
  APP_NAME=$APP_NAME \
  PRIMARY_COLOR=$PRIMARY_COLOR \
  SECONDARY_COLOR=$SECONDARY_COLOR \
  FONT_FAMILY=$FONT_FAMILY \
  SUPPORT_EMAIL=$SUPPORT_EMAIL \
  LOGO_URL=$LOGO_URL \
  CORS_ORIGIN=$CORS_ORIGIN \
  RATE_LIMIT_MAX=$RATE_LIMIT_MAX \
  RATE_LIMIT_TIME_WINDOW=$RATE_LIMIT_TIME_WINDOW \
  ADMIN_APP_URL=$ADMIN_APP_URL \
  CLIENT_APP_URL=$CLIENT_APP_URL \
  TZ=Africa/Lagos

#  Run the app
CMD ["npm", "start"]
